Imports System
Imports Microsoft.VisualBasic.CompilerServices

Namespace RSWINV3
	Friend NotInheritable Module MRes
		Public Enum ResBitmapConstants
			IDB_VISUAL_INPUT = 1000
		End Enum

		Public Enum ResCustomResourceConstants
			IDR_RODSTAR_SCHEMA = 101
		End Enum

		Public Enum ResIconConstants
			IDI_RPTDATA = 8000
			IDI_RPTDATA_A
			IDI_RPTDATA_C
			IDI_RPTDATA_AC
			IDI_RPTCOST
			IDI_RPTIPR
			IDI_RPTIPR_C
			IDI_RPTDYNO
			IDI_RPTDYNO_A
			IDI_RPTDYNO_C
			IDI_RPTDYNO_AC
			IDI_RPTTORQUE
			IDI_RPTTORQUE_C
			IDI_RPTDYNOTORQUE
			IDI_RPTDYNOTORQUE_A
			IDI_RPTDYNOTORQUE_C
			IDI_RPTDYNOTORQUE_AC
		End Enum

		Public Enum ResStringConstants
			IDS_OLD_RUN = 101
			IDS_ASK_SAVE
			IDS_FILE_SAVED
			IDS_FILE_LOADED
			IDS_FILE_LOADED_WITH_OUTPUT
			IDS_ENTER_VALID_NUMBER
			IDS_DEVPROF_MEASDEPTH_MISSING
			IDS_DEVPROF_AZIMUTH_MISSING
			IDS_DEVPROF_AZIMUTH_OORANGE
			IDS_DEVPROF_INCLINATION_MISSING
			IDS_DEVPROF_INCLINATION_OORANGE
		End Enum
	End Module
End Namespace
